M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-21T02:36:29+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-21T02:36:29+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.4764Y-4.4291
X4.4291Y-4.4291
M30
